#!/usr/bin/env python3
"""Runner for the STAR TeamTalk bot.

Usage:
    uv run python run.py            # run with config.py / config.local.py settings
    uv run python run.py --no-star  # connect to TT only, no auto STAR connect
    uv run python run.py --set      # interactive first-time setup -> config.local.py

The `--set` wizard asks for every config field and writes a gitignored
`config.local.py` next to this file. That file is NEVER committed, so your
account details stay on your machine only.
"""
import os
import sys
import argparse
import logging

# ensure the project directory (this file's folder) is importable so the
# sibling modules resolve when run via `uv run python run.py`.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bot
from bot import StarTeamTalkBot, build_bot_from_config
import config  # noqa

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("star_tt_bot.runner")

_HERE = os.path.dirname(os.path.abspath(__file__))
_LOCAL_CFG = os.path.join(_HERE, "config.local.py")

# Field order + prompts for the --set wizard. (key, label, secret?)
_SET_FIELDS = [
    ("host", "TeamTalk server host", False),
    ("tcp_port", "TeamTalk TCP port", False),
    ("udp_port", "TeamTalk UDP port", False),
    ("nickname", "Bot nickname", False),
    ("status", "Bot status message (blank for none)", False),
    ("username", "TeamTalk username", False),
    ("password", "TeamTalk password", True),
    ("channel_path", "Channel path to join (e.g. /hangout area/)", False),
    ("channel_password", "Channel password (blank if none)", True),
    ("encrypted", "Use encrypted connection? (true/false)", False),
    ("star_uri", "Default STAR coagulator URI", False),
]


def _load_existing():
    """Return a dict of currently effective settings (config + local override)."""
    cfg = dict(config.CONFIG)
    try:
        import importlib.util as _ilu
        if os.path.isfile(_LOCAL_CFG):
            spec = _ilu.spec_from_file_location("config_local", _LOCAL_CFG)
            mod = _ilu.module_from_spec(spec)
            spec.loader.exec_module(mod)
            if hasattr(mod, "CONFIG"):
                cfg.update(mod.CONFIG)
    except Exception:
        pass
    return cfg


def _prompt(label, current, secret):
    if secret:
        cur = "***set***" if current else "(empty)"
        val = input(f"{label} [{cur}]: ").strip()
        # empty -> keep existing; a value -> use it; the literal "<empty>" clears
        if val == "":
            return current
        if val.lower() == "<empty>":
            return ""
        return val
    cur = current if current not in (None, "") else "(empty)"
    val = input(f"{label} [{cur}]: ").strip()
    if val == "":
        return current
    return val


def run_setup():
    existing = _load_existing()
    print("\n=== STAR TeamTalk Bot setup ===")
    print("Press Enter to keep the [current] value. Leave password blank to keep it.\n")
    out = {}
    for key, label, secret in _SET_FIELDS:
        cur = existing.get(key, "")
        if key in ("tcp_port", "udp_port"):
            cur = str(cur)
        val = _prompt(label, cur, secret)
        if key in ("tcp_port", "udp_port"):
            try:
                val = int(val)
            except (TypeError, ValueError):
                val = existing.get(key, 0)
        elif key == "encrypted":
            val = str(val).strip().lower() in ("1", "true", "yes", "on")
        out[key] = val

    lines = ["# Auto-generated by `uv run python run.py --set`.",
             "# This file is gitignored -- your credentials stay local.",
             "# Only the keys you set are written; defaults come from config.py.",
             "CONFIG = {"]
    for key, _label, _secret in _SET_FIELDS:
        v = out.get(key, "")
        if isinstance(v, bool):
            lines.append(f"    {key!r}: {v},")
        elif isinstance(v, int):
            lines.append(f"    {key!r}: {v},")
        else:
            lines.append(f"    {key!r}: {v!r},")
    lines.append("}")
    with open(_LOCAL_CFG, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nSaved to {_LOCAL_CFG}")
    print("Run the bot with:  uv run python run.py")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-star", action="store_true", help="do not auto-connect to STAR")
    ap.add_argument("--star-uri", default=None, help="override STAR coagulator URI")
    ap.add_argument("--set", action="store_true", help="interactive setup -> config.local.py")
    args = ap.parse_args()

    if args.set:
        return run_setup()

    cfg = dict(config.CONFIG)
    bot = build_bot_from_config(cfg)

    try:
        bot.connect()
    except Exception as e:
        log.error("Failed to connect/login to TeamTalk: %s", e)
        return 1

    # The default coagulator comes from config/env (star_uri). /coag (in-session)
    # can override it for this run only; it never changes the saved default.
    if not args.no_star and cfg.get("star_uri"):
        try:
            bot.coag.connect(cfg["star_uri"])
            log.info("Auto-connected to STAR coagulator (%d voices)", len(bot.coag.list_voices()))
        except Exception as e:
            log.warning("Could not auto-connect to STAR coagulator: %s", e)

    try:
        bot.run()
    except KeyboardInterrupt:
        log.info("Interrupted by user.")
    finally:
        bot.disconnect()
    return 0


if __name__ == "__main__":
    sys.exit(main())
